#!/bin/sh

##############################################################################
#
#  Gradle start up script for POSIX generated by Gradle.
#
##############################################################################

# Attempt to set APP_HOME
APP_HOME=$( cd "${APP_HOME:-$(dirname "$0")}" > /dev/null 2>&1 && pwd -P ) || exit

# Add default JVM options here
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Collect all arguments for the java command
set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Use the maximum available, or set MAX_FD != -1 to use that value
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in
  CYGWIN* )         cygwin=true  ;;
  Darwin* )         darwin=true  ;;
  MSYS* | MINGW* )  msys=true    ;;
  NonStop* )        nonstop=true ;;
esac

APP_BASE_NAME=$( basename "$0" )
APP_HOME=$( cd "${APP_HOME:-$(dirname "$0")}" > /dev/null 2>&1 && pwd -P ) || exit

# Make sure the wrapper jar exists
WRAPPER_JAR="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"
[ -f "$WRAPPER_JAR" ] || die "ERROR: Gradle wrapper jar not found at $WRAPPER_JAR"

# Collect all arguments for the java command
eval set -- $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS "\"-Dorg.gradle.appname=$APP_BASE_NAME\"" -classpath "\"$WRAPPER_JAR\"" org.gradle.wrapper.GradleWrapperMain "$@"

exec "$JAVACMD" "$@"
